spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/japanese?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: wehoo
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
mybatis:
  type-aliases-package: com.example.demo.lwh.po
logging:
  level:
    root: info
    com.liao: debug
  file: log/blog-dev.log
server:
  port: 8081